[build]
builder = "NIXPACKS"
buildCommand = "npm install --include=dev && npm run build -w backend"

[deploy]
startCommand = "npm run start -w backend"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
